# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Tmicro 2/Desktop/JcTFG/Ethernet/Ethernet.srcs/sources_1/bd/Ethernet/ip/Ethernet_processing_system7_0_0/Ethernet_processing_system7_0_0.xci
# IP: The module: 'Ethernet_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/Ethernet/Ethernet.srcs/sources_1/bd/Ethernet/ip/Ethernet_processing_system7_0_0/Ethernet_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ethernet_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/Tmicro 2/Desktop/JcTFG/Ethernet/Ethernet.srcs/sources_1/bd/Ethernet/ip/Ethernet_processing_system7_0_0/Ethernet_processing_system7_0_0.xci
# IP: The module: 'Ethernet_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/Ethernet/Ethernet.srcs/sources_1/bd/Ethernet/ip/Ethernet_processing_system7_0_0/Ethernet_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ethernet_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
