# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Ethernet/Ethernet.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet || ORIG_REF_NAME==Ethernet}]

# IP: bd/Ethernet/ip/Ethernet_processing_system7_0_0/Ethernet_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_processing_system7_0_0 || ORIG_REF_NAME==Ethernet_processing_system7_0_0}]

# XDC: bd/Ethernet/Ethernet_ooc.xdc
