# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/Ethernet_axi_ethernet_0_0.xci
# IP: The module: 'Ethernet_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/bd_1b50.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1b50 || ORIG_REF_NAME==bd_1b50}]

# IP: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_0/bd_1b50_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1b50_eth_buf_0 || ORIG_REF_NAME==bd_1b50_eth_buf_0}]

# IP: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/bd_1b50_eth_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1b50_eth_mac_0 || ORIG_REF_NAME==bd_1b50_eth_mac_0}]

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/bd_1b50_ooc.xdc

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/synth/Ethernet_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ethernet_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/Ethernet_axi_ethernet_0_0.xci
# IP: The module: 'Ethernet_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/bd_1b50.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1b50 || ORIG_REF_NAME==bd_1b50}]

# IP: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_0/bd_1b50_eth_buf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1b50_eth_buf_0 || ORIG_REF_NAME==bd_1b50_eth_buf_0}]

# IP: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/bd_1b50_eth_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1b50_eth_mac_0 || ORIG_REF_NAME==bd_1b50_eth_mac_0}]

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/bd_1b50_ooc.xdc

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/synth/Ethernet_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Ethernet_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
