# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1b50_eth_mac_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1b50_eth_mac_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1b50_eth_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1b50_eth_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1b50_eth_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1b50_eth_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1b50_eth_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1b50_eth_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1b50_eth_mac_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1b50_eth_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1b50_eth_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1b50_eth_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1b50_eth_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1b50_eth_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1b50_eth_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1b50_eth_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
