# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Ethernet/Ethernet.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet || ORIG_REF_NAME==Ethernet}]

# IP: bd/Ethernet/ip/Ethernet_processing_system7_0_0/Ethernet_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_processing_system7_0_0 || ORIG_REF_NAME==Ethernet_processing_system7_0_0}]

# IP: bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/Ethernet_axi_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_axi_ethernet_0_0 || ORIG_REF_NAME==Ethernet_axi_ethernet_0_0}]

# IP: bd/Ethernet/ip/Ethernet_axi_ethernet_0_dma_0/Ethernet_axi_ethernet_0_dma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_axi_ethernet_0_dma_0 || ORIG_REF_NAME==Ethernet_axi_ethernet_0_dma_0}]

# IP: bd/Ethernet/ip/Ethernet_axi_mem_intercon_0/Ethernet_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_axi_mem_intercon_0 || ORIG_REF_NAME==Ethernet_axi_mem_intercon_0}]

# IP: bd/Ethernet/ip/Ethernet_rst_ps7_0_100M_0/Ethernet_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_rst_ps7_0_100M_0 || ORIG_REF_NAME==Ethernet_rst_ps7_0_100M_0}]

# IP: bd/Ethernet/ip/Ethernet_ps7_0_axi_periph_0/Ethernet_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_ps7_0_axi_periph_0 || ORIG_REF_NAME==Ethernet_ps7_0_axi_periph_0}]

# IP: bd/Ethernet/ip/Ethernet_xbar_0/Ethernet_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_xbar_0 || ORIG_REF_NAME==Ethernet_xbar_0}]

# IP: bd/Ethernet/ip/Ethernet_xbar_1/Ethernet_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_xbar_1 || ORIG_REF_NAME==Ethernet_xbar_1}]

# IP: bd/Ethernet/ip/Ethernet_auto_pc_0/Ethernet_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_auto_pc_0 || ORIG_REF_NAME==Ethernet_auto_pc_0}]

# IP: bd/Ethernet/ip/Ethernet_auto_us_0/Ethernet_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_auto_us_0 || ORIG_REF_NAME==Ethernet_auto_us_0}]

# IP: bd/Ethernet/ip/Ethernet_auto_us_1/Ethernet_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_auto_us_1 || ORIG_REF_NAME==Ethernet_auto_us_1}]

# IP: bd/Ethernet/ip/Ethernet_auto_us_2/Ethernet_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_auto_us_2 || ORIG_REF_NAME==Ethernet_auto_us_2}]

# IP: bd/Ethernet/ip/Ethernet_auto_pc_1/Ethernet_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Ethernet_auto_pc_1 || ORIG_REF_NAME==Ethernet_auto_pc_1}]

# XDC: bd/Ethernet/Ethernet_ooc.xdc
