# 
# Synthesis run script generated by Vivado
# 

set_param project.hsv.suppressChildGraphs 0
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:microzed_7010:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/hdl/Ethernet_wrapper.vhd}}
add_files {{C:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/Ethernet.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_processing_system7_0_0/Ethernet_processing_system7_0_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_0/bd_1b50_eth_buf_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_1b50_eth_buf_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_0/bd_1b50_eth_buf_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1b50_eth_mac_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1b50_eth_mac_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1b50_eth_mac_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_1b50_eth_mac_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/bd_0/bd_1b50_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_0/synth/Ethernet_axi_ethernet_0_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_dma_0/Ethernet_axi_ethernet_0_dma_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_dma_0/Ethernet_axi_ethernet_0_dma_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_axi_ethernet_0_dma_0/Ethernet_axi_ethernet_0_dma_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_rst_ps7_0_100M_0/Ethernet_rst_ps7_0_100M_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_rst_ps7_0_100M_0/Ethernet_rst_ps7_0_100M_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_rst_ps7_0_100M_0/Ethernet_rst_ps7_0_100M_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_xbar_0/Ethernet_xbar_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_xbar_1/Ethernet_xbar_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_auto_pc_0/Ethernet_auto_pc_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_auto_us_0/Ethernet_auto_us_0_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_auto_us_0/Ethernet_auto_us_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_auto_us_1/Ethernet_auto_us_1_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_auto_us_1/Ethernet_auto_us_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_auto_us_2/Ethernet_auto_us_2_clocks.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_auto_us_2/Ethernet_auto_us_2_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/ip/Ethernet_auto_pc_1/Ethernet_auto_pc_1_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/Ethernet_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/Tmicro 2/Desktop/JcTFG/ZynqEthernetCamera_2016/ZynqEthernetCamera_2016.srcs/sources_1/bd/Ethernet/Ethernet.bd}}]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Ethernet_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef Ethernet_wrapper.dcp

catch { report_utilization -file Ethernet_wrapper_utilization_synth.rpt -pb Ethernet_wrapper_utilization_synth.pb }
